# <service_name> <sock_type> <proto> <flags> <user> <server_path> <args>
# ftp	stream	tcp	nowait	root	/usr/sbin/tcpd		in.ftpd
# PREPARO SSH A MI MANERA PARA MAS ADELANTE
# 22 stream tcp nowait root /mnt/onboard/opt/dropbear/dropbearmulti dropbear -i -r /mnt/onboard/opt/dropbear/dss_key -r /mnt/onboard/opt/dropbear/rsa_key -r /mnt/onboard/opt/dropbear/ecdsa_key -B
23 stream tcp nowait root /bin/busybox telnetd -i
