# <service_name> <sock_type> <proto> <flags> <user> <server_path> <args>
# ftp	stream	tcp	nowait	root	/usr/sbin/tcpd		in.ftpd
22 stream tcp nowait root /opt/dropbear/dropbearmulti dropbear -i -r /opt/dropbear/rsa_key -r /opt/dropbear/ecdsa_key -r /opt/dropbear/ed25519_key
23 stream tcp nowait root /bin/busybox telnetd -i
